services:
  - type: web
    name: youtube-transcript-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TRANSCRIPT_MICROSERVICE_URL
        value: https://your-subdomain.onrender.com  # Replace this after deploy